apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: DockerHub
        api_url: https://index.docker.io/v1/
        prefix: docker.io
        credentials:
          username: vaishali293
          password: dckr_pat_iKtjMr7B8mFewApoWXrO1OpDMmc

